name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Load Environment Variables
      run: |
        if [ -f "markIII.io.github_main/github/workflows/docs/variaveis.env" ]; then
          export $(grep -v '^#' markIII.io.github_main/github/workflows/docs/variaveis.env | xargs)
        fi

    - name: Set Schema
      run: echo "workflows=framos500 PPP=vapo" > markIII.io.github_main/github/workflows/docs/schema.json

    - name: Set Schema Variable
      run: echo "::set-env name=SCHEMA::$(cat markIII.io.github_main/github/workflows/docs/schema.json | base64)"

    - name: Debug Schema
      run: echo "Schema: ${{ env.SCHEMA }}"

    - name: Build Jekyll Site
      run: |
        chmod +x markIII.io.github_main/github/workflows/docs/build.sh
        ./markIII.io.github_main/github/workflows/docs/build.sh
