name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create Docs Directory
      run: mkdir -p docs
      working-directory: markIII.io.github_main/github/workflows/docs

    - name: Debug Directories
      run: |
        pwd
        ls -la
        ls -la ./docs

    - name: Setup Ruby
      uses: actions/setup-ruby@v2
      with:
        ruby-version: 2.7

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll
      run: bundle exec jekyll build
      working-directory: markIII.io.github_main/github/workflows/docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
