name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Load Environment Variables
      run: |
        if [ -f "markIII.io.github_main/github/workflows/docs/variaveis.env" ]; then
          export $(grep -v '^#' markIII.io.github_main/github/workflows/docs/variaveis.env | xargs)
        fi

    - name: Set Schema
      run: echo "workflows=framos500 PPP=vapo" > markIII.io.github_main/github/workflows/docs/schema.json

    - name: Set Schema Variable
      run: echo "::set-env name=SCHEMA::$(cat markIII.io.github_main/github/workflows/docs/schema.json | base64)"

   - name: Build Jekyll Site
  run: |
    chmod +x markIII.io.github_main/build.sh
    cd markIII.io.github_main/markIII.io.github_main  # Entre no diretório onde estão os arquivos do Jekyll
    bundle install  # Se ainda não tiver sido feito
    bundle exec jekyll build

    - name: Docker Build
      run: docker build -t my-jekyll-image -f markIII.io.github_main/dockerfile .

    - name: Run Docker Container
      run: docker run -it --rm my-jekyll-image

    - name: Copy HTML and CSS
      run: cp markIII.io.github_main/github/workflows/docs/config_html_css/HTMLteste_1.html markIII.io.github_main/markIII.io.github_main/_site/HTMLteste_1.html
