  # Fluxo de trabalho de exemplo para construir e implantar um site Jekyll nas GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Executa quando ocorre push na branch principal
  push:
    branches:
      - main

  # Permite executar este fluxo de trabalho manualmente na guia Actions
  workflow_dispatch:

# Define permissões do GITHUB_TOKEN para permitir implantação nas GitHub Pages
permissions:
  contents: read
  pages: write

# Permite apenas uma implantação simultânea, ignorando execuções enfileiradas entre a execução em andamento e a última enfileirada.
# No entanto, NÃO cancela execuções em andamento, pois queremos permitir que essas implantações de produção sejam concluídas.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construção
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Atualizado para a versão mais recente
      - name: Configurar GitHub Pages
        uses: actions/setup-node@v4 # Atualizado para a versão mais recente
      - name: Instalar dependências do Jekyll
        run: |
          bundle install
      - name: Construir com Jekyll
        run: |
          bundle exec jekyll build
      - name: Upload do artefato
        uses: actions/upload-artifact@v2 # Atualizado para a versão mais recente
        with:
          name: jekyll-site
          path: _site

  # Job de implantação
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configurar GitHub Pages
        uses: actions/setup-node@v4 # Atualizado para a versão mais recente
      - name: Baixar artefato de construção
        uses: actions/download-artifact@v2 # Atualizado para a versão mais recente
        with:
          name: jekyll-site
          path: _site
      - name: Implantação nas GitHub Pages
        uses: actions/gh-pages@v3 # Atualizado para a versão mais recente
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_dir: _site
