- name: Cérebro e Pensamento
  # You may pin to the exact commit or the version.
  # uses: PHP-Prefixer/php-prefixer-build-action@9008469017553a3b9c0ae85ca2fc3de19f40119f
  uses: PHP-Prefixer/php-prefixer-build-action@v1.1.0
  with:
    # The PHP-Prefixer PAT/Personal Access Token. The token must be configured in the PHP-Prefixer account. Example: `789|1234567890123456789012345678901234567890`.
    personal_access_token: 
    # The project ID to process the source code. The project must be configured in your account in the PHP-Prefixer account. Example: `5123`.
    project_id: 
    # The PHP-Prefixer JSON configuration to be applied to the project. By default, the prefixer uses the configuration present in composer.json. If there is no extra configuration or the extra configuration must be replaced, this parameter overrides the composer.json extra configuration to define the PHP-Prefixer schema. Example: '{"project-name": "Prefixed Project","namespaces-prefix": "PPP","global-scope-prefix": "PPP_"}'
    schema: # optional

- name: Configurar PHP-Prefixer
  uses: PHP-Prefixer/php-prefixer-build-action@v1.1.0
  with:
    personal_access_token: 
    project_id: 
    schema: 

- name: Build com Jekyll
  run: bundle exec jekyll build

- name: Upload do artefato
  uses: actions/upload-artifact@v2 # Atualizado para a versão mais recente
  with:
    name: jekyll-site
    path: _site

- name: Deploy to GitHub Pages
  uses: actions/gh-pages@v3 # Atualizado para a versão mais recente
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    build_dir: _site
