- name: 'Cérebro e Pensamento'
  uses: PHP-Prefixer/php-prefixer-build-action@v1.1.0
  with:
    personal_access_token: ${{ secrets.PREFIXER_TOKEN }}
    project_id: ${{ secrets.PREFIXER_PROJECT_ID }}
    schema: '{"project-name": "Prefixed Project","namespaces-prefix": "PPP","global-scope-prefix": "PPP_"}'

- name: 'Configurar PHP-Prefixer'
  uses: PHP-Prefixer/php-prefixer-build-action@v1.1.0
  with:
    personal_access_token: ${{ secrets.PREFIXER_TOKEN }}
    project_id: ${{ secrets.PREFIXER_PROJECT_ID }}
    schema: ''

- name: 'Build com Jekyll'
  run: 'bundle exec jekyll build'

- name: 'Upload do artefato'
  uses: actions/upload-artifact@v2
  with:
    name: 'jekyll-site'
    path: '_site'

- name: 'Deploy to GitHub Pages'
  uses: actions/gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    build_dir: '_site'
