            - name: New Relic Application Deployment Marker
  # You may pin to the exact commit or the version.
  # uses: newrelic/deployment-marker-action@60142df2a3f5c23d3294486f474299b8f490cd90
  uses: newrelic/deployment-marker-action@v2.5.0
  with:
    # Your New Relic User API Key.
    apiKey: 
    # Your New Relic entity GUID. This entity GUID should be for the entity you are tracking.
    guid: 
    # Custom version information to add to the deployment marker - e.g. the latest tag.
    version: 
    # The geographical region for your New Relic account - US or EU. Default: US
    region: # optional, default is US
    # Description stored with the deployment. Default: <none>
    description: # optional
    # Change log string stored with the deployment. Default: <none>
    changelog: # optional
    # Commit for the deployment.
    commit: # optional
    # Deep link referencing the deployment.
    deeplink: # optional
    # The type of deployment this is conducting.
    deploymenttype: # optional, default is BASIC
    # The user creating the deployment. Default: `github.actor`
    user: # optional, default is ${{ github.actor }}
    # Group Id used to link deployments together.
    groupid: # optional
          
